# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoPayuCoreSDK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DemoPayuCoreSDK

  target 'DemoPayuCoreSDKTests' do
    inherit! :search_paths
    # Pods for testing
  end

   pod 'PayUIndia-PG-SDK'

  target 'DemoPayuCoreSDKUITests' do
    # Pods for testing
  end

end
